development:
  adapter: postgresql
  database: portfolio-lostpages-backend_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: portfolio-lostpages-backend_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: portfolio-lostpages-backend_production
  pool: 5
  timeout: 5000
